### ISSUE TITLE
Undeclared dependnecy on Test::Exception

### ISSUE THREAD

**Issue by andk** [zentooo/Net-OpenID-Connect-IDToken#1]
As per subject. Grep:

http://search.cpan.org/grep?release=Net-OpenID-Connect-IDToken-0.01;string=Test::Exception;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/35916807

HTH && Thanks,

**Comment by zentooo** [comment]
already fixed on v.0.02
